DecoLed/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuarios.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^convert/', include('lazysignup.urls')),
]

api/urls.py
from django.conf.urls import url, include
from . import views
from rest_framework.routers import DefaultRouter

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'orders', views.OrderViewSet)
router.register(r'drinks', views.DrinkViewSet)

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

usuarios/urls.py
from django.conf.urls import url
from .views import index
from . import views
app_name = 'usuarios'

urlpatterns = [
    # url(r'drinks/$', drink_manager, name='drink_manager'),
    url(r'old/^$', index, name='old_index'),
    url(r'^$', views.new_index, name='index'),
    url(r'login/$', views.do_login, name='login'),
    url(r'logout/$', views.do_logout, name='logout'),
    url(r'order_manager/$', views.order_manager, name='order_manager'),
    url(r'drink_manager/$', views.drink_manager, name='drink_manager'),
]

api/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Drink(models.Model):
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=64, blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Order(models.Model):

    choices = [
        ("done", "Listo"),
        ("pending", "Pendiente"),
        ("cancelled", "Cancelado"),
    ]
    status = models.CharField(max_length=64, default="pending", choices=choices)
    user = models.OneToOneField(User, related_name='order', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        if(self.user):
            return "{}'s order.".format(self.user.username)
        else:
            return "Order: {}".format(
            ','.join(['{} {}'.format(
            row.cantity, row.drink.name) for row in self.rows.all()]))


class OrderRow(models.Model):
    order = models.ForeignKey(Order, related_name='rows', on_delete=models.CASCADE)
    drink = models.ForeignKey(Drink, limit_choices_to={'available': True})
    cantity = models.PositiveIntegerField(default=1)

usuarios/models.py
from django.db import models

usuarios/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=64)
    password = forms.CharField(widget=forms.PasswordInput, max_length=64)

api/views.py
from rest_framework import viewsets, status
from . import models
from .serializers import OrderSerializer, DrinkSerializer
from rest_framework.response import Response
from rest_framework import permissions
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authentication import SessionAuthentication
from django.dispatch import Signal

order_created = Signal(providing_args=['instance'])


class CsrfExemptSessionAuthentication(SessionAuthentication):

    def enforce_csrf(self, request):
        return  # To not perform the csrf check previously happening


class OrderViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    queryset = models.Order.objects.all()
    serializer_class = OrderSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    # authentication_classes = (CsrfExemptSessionAuthentication,)

    def perform_create(self, serializer):
        print('Creating order for ', self.request.user)
        serializer.save(user=self.request.user)
        order_created.send(self.__class__, instance=self.request.user.order)

    @csrf_exempt
    def create(self, request, *args, **kwargs):
        if(hasattr(self.request.user, 'order')):
            print('User has an order pending')
            return Response({'error': 'Ya tienes un pedido en progreso.'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            return super(OrderViewSet, self).create(request, *args, **kwargs)


class DrinkViewSet(viewsets.ModelViewSet):
    """
    List, create, edit, delete Drink instances.
    """
    queryset = models.Drink.objects.all()
    serializer_class = DrinkSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

usuarios/views.py
from django.shortcuts import render, redirect, reverse
from .forms import LoginForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from lazysignup.decorators import allow_lazy_user, require_nonlazy_user
from api import models
from django.contrib.auth.decorators import user_passes_test


def do_login(request):
    if(request.method == 'POST'):
        form = LoginForm(request.POST)
        if(form.is_valid()):
            # print(form.cleaned_data)
            user = authenticate(request, **form.cleaned_data)
            if(user is not None):
                login(request, user)
                return redirect(reverse('usuarios:index'))
            else:
                messages.error(request, "Datos de ingreso invalidos.")
                return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})


def do_logout(request):
    logout(request)
    return redirect(reverse('usuarios:index'))


def index(request):
    drinks = models.Drink.objects.filter(available=True)
    # print("DRINKS, ", drinks)
    return render(request, 'home.html', {'drinks': drinks})


@allow_lazy_user
def new_index(request):
    drinks = models.Drink.objects.filter(available=True)
    # print("DRINKS, ", drinks)
    if(models.Order.objects.filter(user=request.user).count()):
        order = request.user.order
        if(order.status in ['cancelled', 'done']):
            order.user = None
            order.save()
        print('ORDER STATUS: ', order.status)
        return render(request, 'user_wait.html', {'order': order})

    return render(request, 'new_home.html', {'drinks': drinks})


@require_nonlazy_user('/login')
@user_passes_test(lambda u: u.is_staff, '/login')
def order_manager(request):
    orders = models.Order.objects.filter(status='pending').exclude(user=None)
    return render(request, 'order_manager.html', {
		'orders': orders,
		'count': models.Order.objects.count()
    })


@require_nonlazy_user('/login')
@user_passes_test(lambda u: u.is_staff, '/login')
def drink_manager(request):
    drinks = models.Drink.objects.all()
    return render(request, 'drink_manager.html', {'drinks': drinks})

usuarios/templates/base.html
{% load static lazysignup_tags %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>DecoLED</title>
    <link rel="stylesheet" href="/style.css" type="text/css"/>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- SockJS library -->
    <script src="https://cdn.jsdelivr.net/sockjs/1.0.1/sockjs.min.js"></script>
  </head>

  <body>
    <!-- Fixed navbar -->
        <nav id="header" class="navbar navbar-default">
            <div id="header-container" class="container navbar-container">
                <div class="navbar-header">
                    <a id="brand" class="navbar-brand" href="/">DecoLED</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                    {% if not user|is_lazy_user %}
                      <li><a href="/profile">Bienvenido, {{ user.get_username }}</a></li>
                    {% else %}
                      <li><a href="{% url 'usuarios:login' %}">Login</a>
                      <li>
                        <a href="#contact">Entrar con Facebook</a>
                      </li>
                    {% endif %}
                    </ul>
                </div><!-- /.nav-collapse -->
            </div><!-- /.container -->
        </nav><!-- /.navbar -->


    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <div id="bottom">
        {% block bottom %}{% endblock %}
    </div>
    <script src="{% static 'usuarios/script.js' %}"></script>
  </body>
</html>

usuarios/templates/drink_manager.html
{% extends 'new_base.html' %}
{% load static %}
{% block content %}
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <div class="container-fluid">
        <div class="row">
			<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4" >
				<div>
				    <div class="panel-body" style="background-color: initial;">
						<form role="form">
							<fieldset>
                            {% for drink in drinks %}
                                <div class="form-group">
                                {% if drink.available %}
                                    <button type="button" id="{{ drink.id }}" class="btn btn-success btn-drink-toggle btn-block">
                                    {{ drink.name }}
                                    </button>
                                {% else %}
                                    <button type="button" id="{{ drink.id }}" class="btn btn-danger btn-drink-toggle btn-block">
                                    {{ drink.name }}
                                    </button>
	                            {% endif %}
							    </div>
                            {% endfor %}
							</fieldset>
                            {% if not drinks.count %}
                            <b>Parece que no hay tragos todavia.</b>
                            {% endif %}
					    </form>
					</div>
		        </div>
		    </div>
		</div>
    </div>
{% endblock %}

{% block bottom %}

 <script src="{% static 'usuarios/admin.js' %}"></script>
 <script>
     $('.navprofile').first().toggleClass('active');
     $('.navdrinks').first().toggleClass('active');
 </script>
{% endblock %}

usuarios/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-2">0</div>
        <div class="col-xs-4">
			<select id="drink_id" name="drink">
				{% for drink in drinks %}
					{% if forloop.first %}
						<option value="{{ drink.id }}" selected>{{ drink.name }}</option>
					{% else %}
						<option value="{{ drink.id }}">{{ drink.name }}</option>
					{% endif %}
				{% endfor %}
			</select>
		</div>
        <div class="col-xs-2">+</div>
        <div class="col-xs-2">-</div>
    </div>
</div>
<div class="btn-group">
    <a href="#" class="btn btn"><i class="icon icon-fast-backward"></i></a>
    <a href="#" class="btn btn"><i class="icon icon-backward"></i></a>
    <a href="#" class="btn btn"><i class="icon icon-stop"></i></a>
    <a href="#" class="btn btn"><i class="icon icon-play"></i></a>
    <a href="#" class="btn btn"><i class="icon icon-pause"></i></a>
    <a href="#" class="btn btn"><i class="icon icon-forward"></i></a>
    <a href="#" class="btn btn"><i class="icon icon-fast-forward"></i></a>
</div>
{% endblock %}

usuarios/templates/login.html
{% extends 'new_base.html' %}
{% block content %}
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <div class="container-fluid">
        <div class="row">
			<div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 " >
				<div>

				    <div class="panel-body" style="background-color: inherit">
						<form role="form" method="post" id='form_login' action="{% url 'usuarios:login' %}">
							{% csrf_token %}
							<fieldset>
							    <div class="form-group">
							    	<label>Usuario:</label>
							        {{ form.username }}
							    </div>
							    <div class="form-group">
							    	<label>Contraseña:</label>
							        {{ form.password }}
							    </div>
                                <button class="btn btn-lg btn-success btn-block" type="submit" name="login"/>Login</button>
							</fieldset>
					    </form>
					</div>
		        </div>
		    </div>
		</div>
    </div>

{% endblock %}

usuarios/templates/new_base.html
{% load static lazysignup_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta property="api-url" content="{% url 'api:order-list' %}" />
    <title>DecoLED</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'usuarios/cover.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <!-- Font Awesome Icons -->
    <script src="https://use.fontawesome.com/5439a08299.js"></script>
  </head>

  <body>

{% comment %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.10&appId=123718794978316";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endcomment %}

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                  <i class="fa fa-bars" aria-hidden="true"></i>
                </button>
				<a href="{% url 'usuarios:index' %}">DecoLED</a>
			  </h3>



              <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right masthead-nav">
                  {% if not user|is_lazy_user or user.groups.all.count %}
                  <li class="navprofile active">
                    <a href="#">
                      Hola, {{ user.get_short_name }}
                    </a>


                  </li>
                  {% if user.is_staff %}
                  <li class="navorders">
                    <a  href="{% url 'usuarios:order_manager' %}"><span class="fa fa-calendar-minus-o"></span> Pedidos</a></li>
                  <li class="navdrinks">
                    <a href="{% url 'usuarios:drink_manager' %}"><span class="fa fa-glass" ></span> Tragos</a></li>
                  {% endif %}
                  <li>
                    <a href="{% url 'usuarios:logout' %}"><span class="fa fa-sign-out"></span> Salir</a></li>
                  {% else %}

                  <li class="active">
                    <div class="fb-login-button" data-max-rows="1" data-size="medium" data-button-type="login_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>
                    {# <!--<div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="false"></div>--> #}
                  </li>

                  {% endif %}
                </ul>
              </div>
            </div>
          </div>

          <div class="inner cover">
            {% block content %}
            <h1 class="cover-heading">Default page.</h1>
            <p class="lead">
              We will put something interesting here soon :)
            </p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-default">I will do nothing.</a>
            </p>
            {% endblock %}
          </div>

          <div class="mastfoot">
            {% block bottom %}
            {% endblock %}
            {% block footer %}
            <div class="inner">
              <p>DecoLED 2017, Siguenos en <a href="https://facebook.com/DecoLED13/">Facebook</a>.</p>
			</div>
			{% endblock %}
      </div>

    </div>
  <script>
  window.drf = {
    csrfHeaderName: "X-CSRFTOKEN",
    csrfCookieName: "csrftoken"
  };
  </script>
  <script src="{% static 'rest_framework/js/csrf.js' %}"></script>

  </body>
</html>

usuarios/templates/new_home.html
{% extends "new_base.html" %}
{% load static lazysignup_tags %}
{% block content %}
{% csrf_token %}
{% for drink in drinks %}
<div class="row drink-row" id="drink_row_{{ drink.id }}">
  <div class="col-xs-2" id="drink_counter_{{ drink.id }}">0</div>
  <div class="col-xs-6">{{ drink.name }}</div>
  <div class="col-xs-2">
	  <button type="button" class="btn btn-primary btn-circle btn-up" id="drink_up_{{ drink.id }}">
        <i class="glyphicon glyphicon-chevron-up"></i>
      </button>
  </div>
  <div class="col-xs-2">
	  <button type="button" class="btn btn-primary btn-circle btn-down" id="drink_down_{{ drink.id }}">
        <i class="glyphicon glyphicon-chevron-down"></i>
      </button>
  </div>
</div>
{% endfor %}
<br>
{% if drinks %}
<div class="row">
    {% if not user|is_lazy_user or user.groups.all.count %}
        <div class="col-xs-10">
            <input type="text" class="form-control" value="{{ user.get_short_name }}">
        </div>
    {% else %}
        <div class="col-xs-10">
            <input type="text" class="form-control" placeholder="Nombre y Apellido">
        </div>
    {% endif %}
	<div class="col-xs-2">
		<button type="button" class="btn btn-success btn-circle btn-ok"><i class="fa fa-check"></i></button>
	</div>
</div>
{% else %}
<b>La barra se encuentra fuera de servicio hasta el proximo evento.<br>
Para mas información ingrese a nuestra <a style="color:blue" href="https://facebook.com/DecoLED13/">Fanpage</a>
</b>
{% endif %}

{% endblock %}
{% block bottom %}
<script src="{% static 'usuarios/script.js' %}"></script>
{% endblock %}

usuarios/templates/order_manager.html
{% extends "new_base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-xs-6 col-sm-offset-2 col-sm-4">Nombre y Apellido</div>
    <div class="col-xs-4 col-sm-3">Acciones</div>
    <div class="col-xs-2 col-sm-1">
        <button type="button" class="btn btn-primary btn-circle" data-toggle="tooltip" id="btn-refresh">
            <i class="fa fa-refresh"></i>
        </button>
    </div>
</div>

{% for order in orders %}
<div class="row order-row" id="order_row_{{ order.id }}">
    <div class="col-xs-6 col-sm-offset-2 col-sm-5">{{ order.user.get_short_name }}</div>
    <div class="col-xs-2 col-sm-1">
        <button type="button" class="btn btn-success btn-circle btn-done" onclick="acceptOrderCallback(this)">
            <i class="glyphicon glyphicon-ok"></i>
        </button>
    </div>
    <div class="col-xs-2 col-sm-1">
        <button type="button" class="btn btn-danger btn-circle btn-cancel" onclick="cancelOrderCallback(this)">
            <i class="glyphicon glyphicon-remove"></i>
        </button>
    </div>
    <div class="col-xs-2 col-sm-1">
	    <button type="button" class="btn btn-primary btn-circle btn-details" data-toggle="collapse" data-target="#drink_details_{{ order.id }}">
            <i class="glyphicon glyphicon-plus"></i>
        </button>
    </div>
</div>

<div class="row collapse" id="drink_details_{{ order.id }}">
    {% if not order.rows.all %}
    <b>Este pedido no tiene renglones, favor de cancelarlo.</b>
    {% else %}
    <ul>
    {% for order_row in order.rows.all %}
        <li><b>{{ order_row.cantity }}</b> {{ order_row.drink.name }}</li>
    {% endfor %}
    </ul>
    {% endif %}
</div>
{% endfor %}

{% if not orders.count %}
<b class="no-orders">Parece que no hay pedidos todavia.</b>
{% endif %}

{% endblock %}

{% block bottom %}

<script src="{% static 'usuarios/admin.js' %}"></script>

{% endblock %}

{% block footer %}

<div class="inner">
    <p>Pedidos totales: 
        <span class="counter_span" style="color:white">{{ count }}</span>. 
        <a class="clean_database" style="color:red" href="#">Limpiar</a>
    </p>
</div>

{% endblock %}

usuarios/templates/order_template.html
<div class="row order-row" id="order_row_{{ order.id }}">
    <div class="col-xs-6 col-sm-offset-2 col-sm-5">{{ order.user.get_short_name() }}</div>
    <div class="col-xs-2 col-sm-1">
        <button type="button" class="btn btn-success btn-circle btn-done" onclick="acceptOrderCallback(this)">
            <i class="glyphicon glyphicon-ok"></i>
        </button>
    </div>
    <div class="col-xs-2 col-sm-1">
        <button type="button" class="btn btn-danger btn-circle btn-cancel" onclick="cancelOrderCallback(this)">
            <i class="glyphicon glyphicon-remove"></i>
        </button>
    </div>
    <div class="col-xs-2 col-sm-1">
        <button type="button" class="btn btn-primary btn-circle btn-details" data-toggle="collapse" data-target="#drink_details_{{ order.id }}">
            <i class="glyphicon glyphicon-plus"></i>
        </button>
    </div>
</div>
<div class="row collapse" id="drink_details_{{ order.id }}">
    {% if not order.rows.all() %}
    <b>Este pedido no tiene renglones, favor de cancelarlo.</b>
    {% else %}
    <ul>
        {% for order_row in order.rows.all() %}
        <li>
            <b>{{ order_row.cantity }}</b> {{ order_row.drink.name }}
        </li>
        {% end %}
    </ul>
    {% end %}
</div>

usuarios/templates/profile.html
{% extends "base.html" %}
{% block content %}
    Profile
{% endblock %}

usuarios/templates/status_template.html
{% if status == 'pending' %}
<div class="panel panel-warning">
    <div class="panel-heading">
        <h3 class="panel-title">Su pedido esta siendo procesado</h3>
    </div>
    <div class="panel-body">
        <form role="form">
            <fieldset>
                <div class="form-group">
                    Su pedido se encuentra pendiente de ser procesado, por favor espere.<br>
                    Sera avisado cuando este se encuentre listo.
                </div>
            </fieldset>
        </form>
    </div>
    <div class="panel-footer">
        <button type="button" class="btn btn-primary btn-circle" data-toggle="tooltip" id="btn-refresh">
            <i class="fa fa-refresh"></i>
        </button>
    </div>
</div>
{% end %}

{% if status == 'cancelled' %}
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Su pedido ha sido cancelado</h3>
    </div>
    <div class="panel-body">
        Su pedido ha sido cancelado, por favor realice su pedido de nuevo.<br>
        Cualquier duda, consulte con el administrador.
    </div>
    <div class="panel-footer">
        <button type="button" class="btn btn-danger btn-circle btn-reload" onclick="location.reload()">
            <i class="glyphicon glyphicon-remove"></i>
        </button>
    </div>
</div>
{% end %}

{% if status == 'done' %}
<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Pedido listo!</h3>
    </div>
    <div class="panel-body">
        Su pedido esta listo para ser retirado en la barra.<br>
        Muchas gracias por usar nuestro servicio.
    </div>
    <div class="panel-footer">
        <button type="button" class="btn btn-success btn-circle btn-reload" onclick="location.reload()">
            <i class="glyphicon glyphicon-ok"></i>
        </button>
    </div>
</div>
{% end %}

usuarios/templates/user_wait.html
{% extends 'new_base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4" >
        {% if order.status == 'pending' %}
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">Su pedido esta siendo procesado</h3>
            </div>
            <div class="panel-body">
                <form role="form">
                    <fieldset>
                        <div class="form-group">
                            Su pedido se encuentra pendiente de ser procesado, por favor espere.<br>
                            Sera avisado cuando este se encuentre listo.
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="panel-footer">
                <button type="button" class="btn btn-primary btn-circle" data-toggle="tooltip" id="btn-refresh">
                    <i class="fa fa-refresh"></i>
                </button>
            </div>
        </div>
        {% endif %}

        {% if order.status == 'done' %}
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Pedido listo!</h3>
            </div>
            <div class="panel-body">
                Su pedido esta listo para ser retirado en la barra.<br>
                Muchas gracias por usar nuestro servicio.
            </div>
            <div class="panel-footer">
                <button type="button" class="btn btn-success btn-circle btn-reload">
                    <i class="glyphicon glyphicon-ok"></i>
                </button>
            </div>
        </div>
        {% endif %}

        {% if order.status == 'cancelled' %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Su pedido ha sido cancelado</h3>
            </div>
            <div class="panel-body">
                Su pedido ha sido cancelado, por favor realice su pedido de nuevo.<br>
                Cualquier duda, consulte con el administrador.
            </div>
            <div class="panel-footer">
                <button type="button" class="btn btn-danger btn-circle btn-reload">
                    <i class="glyphicon glyphicon-remove"></i>
                </button>
            </div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock %}

{% block bottom %}
<script src="{% static 'usuarios/script.js' %}"></script>

{% if order.status == 'pending' %}
<script>
$(document).ready(function() {
    updater.start();
    $('[data-toggle="tooltip"]').tooltip({
        title: getWebsocketStatus,
        trigger: 'hover',
    });
});
</script>
{% endif %}

{% endblock %}